name: Kompose Convert on Main Branch

on:
  push:
    branches:
      - develop

jobs:
  kompose-convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker build & push to docker repo
      run: |
          docker login docku.ddns.net -u kluster -p Klusterjoa18!
          docker build -t dockertest13:latest -f Dockerfile .
          docker tag dockertest13:latest docku.ddns.net/library/gurwls0122_dockertest13:latest
          docker push docku.ddns.net/library/gurwls0122_dockertest13:latest
    # Add additional steps here to deploy the generated Kubernetes resources.
    - name: CI Completed
      run:  |
        curl -H "Content-Type: application/json" -d '{ "repositoryName": "dockertest13", "githubUsername": "gurwls0122"}' -X POST https://kuploy.ddns.net/server/github/action-completed
