name: Kompose Convert on Main Branch

on:
  push:
    branches:
      - develop

jobs:
  kompose-convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker build & push to docker repo
      run: |
          docker login -u gurwls0122 -p rlagurwls159!
          docker build -t gurwls0122/dockertest6 -f Dockerfile .
          docker push gurwls0122/dockertest6
    # Add additional steps here to deploy the generated Kubernetes resources.
    - name: CI Completed
      run:  |
        curl -H "Content-Type: application/json" -d '{ "repositoryName": "dockertest6", "githubUsername": "gurwls0122"}' -X POST http://kluster.iptime.org:9001/github/action-completed
